### ISSUE TITLE
OSL : 지문형태의 텍스쳐제작. 스컬프쉐이더로 사용한다.

### ISSUE THREAD

**Issue by khw7096** [lazypic/blender#3]
- ref : https://zbrushfun.wordpress.com/2014/02/09/clay-material-for-cycles/

**Comment by khw7096** [comment]
- ref : http://blendersushi.blogspot.kr/2013/08/osl-disk-grid.html

**Comment by khw7096** [comment]
https://www.blendermarket.com/products/claydoh

**Comment by khw7096** [comment]
게임,영상 모두 활용될 수 있는 솔루션이 아니므로 같은 이슈로 닫는다.

**Comment by yoonjieun** [comment]
> * ref : https://zbrushfun.wordpress.com/2014/02/09/clay-material-for-cycles/

private라는데용

**Comment by khw7096** [comment]
바뀌었나봐요.
