### ISSUE TITLE
경로규약 설정하기.

### ISSUE THREAD

**Issue by khw7096** [lazypic/blender#8]
S3에 퍼블리쉬하는 경로의 규약.

- shot : lazypicS3/{project}/{episode}/{scene}/{cut}/filename.blend
- assets : lazypicS3/assets/{type}/filename.blend

**Comment by khw7096** [comment]
- bam 참고할것. https://docs.blender.org/manual/en/dev/pipeline/bam.html#installing-bam

**Comment by khw7096** [comment]
윤지가 하는 프로젝트와 내가하는 프로젝트의 경로 구조가 다르다. 유연한 방법을 고민하기ㅣ

**Comment by yoonjieun** [comment]
> * bam 참고할것. https://docs.blender.org/manual/en/dev/pipeline/bam.html#installing-bam

링크가 깨집니당

**Comment by khw7096** [comment]
https://docs.blender.org/manual/en/2.79/pipeline/bam.html

블랜더 2.8에서는 안되나봐요. 2.79 문서를 다시 붙힙니다.

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/75565001-85838180-5a90-11ea-9930-8133b0d80b36.png)

csi에 경로를 설정할 수 있는 기능을 제작완료.
